version: '3'
services:
    go-hello:
        build: .
        image: codebadger/mini-weather
        networks:
            - reverseproxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.backend=mini-weather"
            - "traefik.frontend.rule=Host:mini-weather.wtakumi.io"
            - "traefik.docker.network=traefik_reverseproxy"
        ports:
        - "4200:4200"

networks:
    reverseproxy:
        external:
            name: traefik_reverseproxy